### ISSUE TITLE
What memory order mode should be used for aggregating the buckets?

### ISSUE THREAD

**Issue by asarkar** [serdaroquai/N26-Coding-Challenge#1]
I came across this repo while working on my own solution for this problem (https://github.com/asarkar/txn-stats). Your solution is impressive, although I think my explanation is clearer :)

While aggregating the buckets into a larger bucket.,I'm wondering what memory order mode should be used. Currently, plain is used, which is the weakest, and has the semantics of reading as if the variable was declared non-volatile. Have you given it some thought?

FWIW, I've also opened a [SO question](https://stackoverflow.com/q/56928437/839733).

**Comment by serdaroquai** [comment]
I did not know about JDK 9 memory order modes until you mentioned them, so thank you for bringing it up. I will make sure to give it a good read. However it is stated [here](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/atomic/package-summary.html), an `AtomicReferenceArray ` provides volatile access semantics for its array elements.  so I am not sure if usage of 'plain' is a correct statement.

hope this repo has been helpful and good luck with your process :)

**Comment by asarkar** [comment]
It doesn’t provide volatile access mode by default, depends on what method you use. You’re using `get`, that’s plain access.

**Comment by serdaroquai** [comment]
Can you please provide a reference for your argument because quoting the same link,

> The memory effects for accesses and updates of atomics generally follow the rules for volatiles, as stated in The Java Language Specification (17.4 Memory Model):
> 
> get has the memory effects of reading a volatile variable.

**Comment by asarkar** [comment]
You’re right, I missed up the calls. [AtomicReference.get](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/concurrent/atomic/AtomicReferenceArray.html#get(int)) has the semantics of `VarHandle.getVolatile` but [VarHandle.get](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/invoke/VarHandle.html#get(java.lang.Object...)) has the semantics of plain. My code (and yours) doesn’t need volatile access IMO, I’ll change that. Closing this ticket, but feel free to add your thoughts.
